# -*- coding: utf-8 -*-
"""hr-havok_lyapunov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVyhmk31900-Kk1JNo7U0Dlfbw4KFkBo
"""

!pip install pydmd

import numpy as np
import matplotlib.pyplot as plt

from scipy.integrate import solve_ivp
from scipy.signal import find_peaks, lsim, StateSpace
from pydmd import HAVOK


# ============================================================
# Hindmarsh-Rose model
# ============================================================

def hindmarsh_rose(
    t,
    state,
    a=1.0,
    b=3.0,
    c=1.0,
    d=5.0,
    r=0.0021,
    s=4.0,
    x_rest=-1.6,
    I_ext=3.281,
):
    x, y, z = state

    dx = y - a*x**3 + b*x**2 - z + I_ext
    dy = c - d*x**2 - y
    dz = r * (s*(x - x_rest) - z)

    return np.array([dx, dy, dz])


def generate_hr_data(t_eval, y0=None, **params):
    if y0 is None:
        y0 = [0.0, 0.0, 0.0]

    sol = solve_ivp(
        lambda t, state: hindmarsh_rose(t, state, **params),
        [t_eval[0], t_eval[-1]],
        y0=y0,
        t_eval=t_eval,
        method="RK45",
        rtol=1e-9,
        atol=1e-11,
    )

    if not sol.success:
        raise RuntimeError(sol.message)

    return sol.y


# ============================================================
# Burst detection
# ============================================================

def get_burst_indices(
    x,
    dt,
    height=0.0,
    min_spike_gap=5.0,
    min_burst_gap=50.0,
):
    spike_idx, _ = find_peaks(
        x,
        height=height,
        distance=int(min_spike_gap / dt)
    )

    if len(spike_idx) == 0:
        return np.array([], dtype=int)

    gap_samples = int(min_burst_gap / dt)

    first_spikes = [spike_idx[0]]
    for i in range(1, len(spike_idx)):
        if spike_idx[i] - spike_idx[i - 1] > gap_samples:
            first_spikes.append(spike_idx[i])

    burst_onsets = []
    for spike in first_spikes:
        search_start = max(0, spike - int(50 / dt))
        segment = x[search_start:spike]
        above = (segment > height).astype(int)
        crossings = np.where(np.diff(above) == 1)[0]

        if len(crossings) > 0:
            burst_onsets.append(search_start + crossings[-1])
        else:
            burst_onsets.append(spike)

    return np.array(burst_onsets, dtype=int)


def get_forcing_burst_indices(
    forcing,
    dt,
    threshold,
    min_burst_gap=30.0,
):
    active = np.abs(forcing) > threshold
    transitions = np.diff(active.astype(int))

    onsets = np.where(transitions == 1)[0] + 1
    offsets = np.where(transitions == -1)[0] + 1

    if active[0]:
        onsets = np.insert(onsets, 0, 0)
    if active[-1]:
        offsets = np.append(offsets, len(forcing) - 1)

    if len(onsets) == 0:
        return np.array([], dtype=int)

    gap_samples = int(min_burst_gap / dt)

    merged = [onsets[0]]
    for i in range(1, len(onsets)):
        gap = onsets[i] - offsets[i - 1]
        if gap > gap_samples:
            merged.append(onsets[i])

    return np.array(merged, dtype=int)


# ============================================================
# Prediction metrics
# ============================================================

def compute_recall_vs_window(
    true_onsets,
    forcing,
    dt,
    threshold,
    windows=[20.0],
):
    results = []

    for window in windows:
        window_samples = int(window / dt)
        TP = 0
        FN = 0

        for burst_start in true_onsets:
            f_start = max(0, burst_start - window_samples)
            f_end = min(burst_start, len(forcing))

            if f_end <= f_start:
                continue

            if np.any(np.abs(forcing[f_start:f_end]) > threshold):
                TP += 1
            else:
                FN += 1

        recall = TP / (TP + FN) if (TP + FN) > 0 else np.nan
        results.append({"window": window, "TP": TP, "FN": FN, "recall": recall})

    return results


def compute_precision_vs_window(
    true_onsets,
    pred_onsets,
    dt,
    windows=[20.0],
):
    results = []

    for window in windows:
        window_samples = int(window / dt)
        TP = 0
        FP = 0

        for pred in pred_onsets:
            future = true_onsets[true_onsets >= pred]

            if len(future) > 0 and (future[0] - pred) <= window_samples:
                TP += 1
            else:
                FP += 1

        precision = TP / (TP + FP) if (TP + FP) > 0 else np.nan
        results.append({"window": window, "TP": TP, "FP": FP, "precision": precision})

    return results


def compute_lead_times(true_onsets, pred_onsets, t, max_lead=None):
    lead_times = []

    for true_idx in true_onsets:
        preds_before = pred_onsets[pred_onsets < true_idx]

        if len(preds_before) == 0:
            continue

        lead = t[true_idx] - t[preds_before[-1]]

        if max_lead is None or lead <= max_lead:
            lead_times.append(lead)

    return np.array(lead_times)


# ============================================================
# Windowed short-term HAVOK R²
# ============================================================

def compute_windowed_havok_r2(
    havok,
    window_size=200,
    n_windows=100,
    random_seed=0,
):
    """
    Computes short-term HAVOK R² by restarting prediction
    at the beginning of each short window.

    This avoids measuring long-term chaotic divergence.
    """

    rng = np.random.default_rng(random_seed)

    V = havok.delay_embeddings
    forcing = havok.forcing
    num_chaos = havok._num_chaos

    V_linear = V[:, :-num_chaos]

    A = havok.A
    B = havok.B

    C = np.eye(A.shape[0])
    D = np.zeros((A.shape[0], B.shape[1]))

    sys = StateSpace(A, B, C, D)

    n = min(len(V_linear), len(forcing), len(havok.time))

    if n <= window_size:
        return np.nan, []

    dt = havok.time[1] - havok.time[0]

    starts = rng.integers(0, n - window_size, size=n_windows)

    r2_values = []

    for start in starts:
        end = start + window_size

        V_true_window = V_linear[start:end]
        forcing_window = forcing[start:end]

        T = np.arange(window_size) * dt

        # KEY FIX:
        # restart prediction from the true HAVOK state
        # at the beginning of the window
        V0 = V_true_window[0]

        V_pred_window = lsim(
            sys,
            U=forcing_window,
            T=T,
            X0=V0
        )[1]

        ss_res = np.sum((V_true_window - V_pred_window) ** 2)
        ss_tot = np.sum((V_true_window - np.mean(V_true_window, axis=0)) ** 2)

        if ss_tot > 0:
            r2_values.append(1 - ss_res / ss_tot)

    return float(np.mean(r2_values)), r2_values


# ============================================================
# Largest Lyapunov exponent
# ============================================================

def estimate_largest_lyapunov(
    params,
    y0=np.array([0.0, 0.0, 0.0]),
    transient_time=500.0,
    total_time=3000.0,
    renorm_time=1.0,
    delta0=1e-8,
):
    sol = solve_ivp(
        lambda t, y: hindmarsh_rose(t, y, **params),
        [0, transient_time],
        y0,
        method="RK45",
        rtol=1e-9,
        atol=1e-11,
    )

    if not sol.success:
        return np.nan

    y_ref = sol.y[:, -1]

    direction = np.random.randn(3)
    direction = direction / np.linalg.norm(direction)
    y_pert = y_ref + delta0 * direction

    n_steps = int(total_time / renorm_time)
    log_growth = []
    current_time = 0.0

    for _ in range(n_steps):
        t_span = [current_time, current_time + renorm_time]

        sol_ref = solve_ivp(
            lambda t, y: hindmarsh_rose(t, y, **params),
            t_span,
            y_ref,
            method="RK45",
            rtol=1e-9,
            atol=1e-11,
        )

        sol_pert = solve_ivp(
            lambda t, y: hindmarsh_rose(t, y, **params),
            t_span,
            y_pert,
            method="RK45",
            rtol=1e-9,
            atol=1e-11,
        )

        if not sol_ref.success or not sol_pert.success:
            return np.nan

        y_ref = sol_ref.y[:, -1]
        y_pert = sol_pert.y[:, -1]

        delta = y_pert - y_ref
        dist = np.linalg.norm(delta)

        if dist == 0 or not np.isfinite(dist):
            continue

        log_growth.append(np.log(dist / delta0))

        delta = delta / dist
        y_pert = y_ref + delta0 * delta

        current_time += renorm_time

    if len(log_growth) == 0:
        return np.nan

    return np.sum(log_growth) / (len(log_growth) * renorm_time)


# ============================================================
# Single HAVOK analysis
# ============================================================

def run_single_havok_analysis(
    params,
    dt=0.1,
    m=120000,
    transient_time=950.0,
    svd_rank=15,
    delays=100,
    forcing_p=0.2,
    prediction_window=20.0,
    short_window_size=200,
    n_short_windows=100,
    make_plot=True,
):
    t = np.arange(m) * dt
    X = generate_hr_data(t, **params)

    transient = int(transient_time / dt)
    x = X[0, transient:]
    t = t[transient:] - t[transient]

    true_onsets = get_burst_indices(x, dt)

    havok = HAVOK(
        svd_rank=svd_rank,
        delays=delays,
        num_chaos=1
    )

    havok.fit(x, t)

    forcing = havok.forcing[:, 0]
    forcing_time = t[:len(forcing)]
    threshold = havok.compute_threshold(forcing=0, p=forcing_p)

    pred_onsets = get_forcing_burst_indices(forcing, dt, threshold)

    recall = compute_recall_vs_window(
        true_onsets=true_onsets,
        forcing=forcing,
        dt=dt,
        threshold=threshold,
        windows=[prediction_window]
    )[0]["recall"]

    precision = compute_precision_vs_window(
        true_onsets=true_onsets,
        pred_onsets=pred_onsets,
        dt=dt,
        windows=[prediction_window]
    )[0]["precision"]

    ibi = np.diff(t[true_onsets]) if len(true_onsets) > 1 else np.array([])
    max_lead = 0.5 * np.min(ibi) if len(ibi) > 0 else None

    lead_times = compute_lead_times(true_onsets, pred_onsets, t, max_lead=max_lead)
    mean_lead = np.nanmean(lead_times) if len(lead_times) > 0 else np.nan

    # NEW correct short-term R²:
    # restart HAVOK prediction at each local window
    short_r2_mean, short_r2_values = compute_windowed_havok_r2(
        havok,
        window_size=short_window_size,
        n_windows=n_short_windows,
        random_seed=0
    )

    if make_plot:
        n_plot = min(15000, len(x), len(forcing))
        t_plot = t[:n_plot]
        x_plot = x[:n_plot]
        f_plot = forcing[:n_plot]

        true_in_range = true_onsets[true_onsets < n_plot]
        pred_in_range = pred_onsets[pred_onsets < n_plot]

        fig, axes = plt.subplots(3, 1, figsize=(14, 8), sharex=True)
        fig.suptitle("HAVOK on Hindmarsh-Rose — Burst Detection", fontsize=14)

        axes[0].plot(t_plot, x_plot, c="k", lw=0.7)
        axes[0].vlines(
            t[true_in_range],
            x_plot.min(),
            x_plot.max(),
            color="tab:blue",
            lw=1,
            alpha=0.7,
            label="True burst onset"
        )
        axes[0].set_ylabel("x(t)")
        axes[0].set_title("Membrane potential")
        axes[0].legend(fontsize=8)

        axes[1].plot(forcing_time[:n_plot], f_plot, c="gray", lw=0.7)
        axes[1].fill_between(
            forcing_time[:n_plot],
            f_plot,
            where=np.abs(f_plot) > threshold,
            color="tab:red",
            alpha=0.45,
            label="Active forcing"
        )
        axes[1].axhline(threshold, c="tab:red", ls="--", lw=1)
        axes[1].axhline(-threshold, c="tab:red", ls="--", lw=1)
        axes[1].vlines(
            t[pred_in_range],
            f_plot.min(),
            f_plot.max(),
            color="tab:orange",
            lw=1,
            alpha=0.8,
            label="Predicted onset"
        )
        axes[1].set_ylabel(r"$v_r$")
        axes[1].set_title("HAVOK forcing term")
        axes[1].legend(fontsize=8)

        axes[2].plot(t_plot, x_plot, c="k", lw=0.5, alpha=0.5)
        axes[2].vlines(
            t[true_in_range],
            x_plot.min(),
            x_plot.max(),
            color="tab:blue",
            lw=1.2,
            label="True"
        )
        axes[2].vlines(
            t[pred_in_range],
            x_plot.min(),
            x_plot.max(),
            color="tab:orange",
            lw=1.2,
            ls="--",
            label="Predicted"
        )
        axes[2].set_xlabel("Time")
        axes[2].set_ylabel("x(t)")
        axes[2].set_title("Burst alignment")
        axes[2].legend(fontsize=8)

        plt.tight_layout()
        plt.show()

    return {
        "x": x,
        "t": t,
        "forcing": forcing,
        "threshold": threshold,
        "true_onsets": true_onsets,
        "pred_onsets": pred_onsets,
        "recall": recall,
        "precision": precision,
        "mean_lead": mean_lead,
        "short_r2_mean": short_r2_mean,
        "short_r2_values": short_r2_values,
        "n_true_bursts": len(true_onsets),
        "n_pred_bursts": len(pred_onsets),
    }


# ============================================================
# Parameter sweep
# ============================================================

def sweep_parameter(
    param_name,
    values,
    base_params,
    dt=0.1,
    m=80000,
    lyap_total_time=1500.0,
    prediction_window=20.0,
    short_window_size=200,
    n_short_windows=100,
):
    results = []

    for value in values:
        print(f"\nRunning {param_name} = {value:.5f}")

        params = base_params.copy()
        params[param_name] = value

        try:
            lam = estimate_largest_lyapunov(
                params,
                total_time=lyap_total_time
            )

            havok_result = run_single_havok_analysis(
                params,
                dt=dt,
                m=m,
                prediction_window=prediction_window,
                short_window_size=short_window_size,
                n_short_windows=n_short_windows,
                make_plot=False
            )

            results.append({
                param_name: value,
                "lambda_max": lam,
                "recall": havok_result["recall"],
                "precision": havok_result["precision"],
                "mean_lead": havok_result["mean_lead"],
                "short_r2_mean": havok_result["short_r2_mean"],
                "n_true_bursts": havok_result["n_true_bursts"],
                "n_pred_bursts": havok_result["n_pred_bursts"],
            })

            print(
                f"lambda={lam:.5f}, "
                f"R2_window={havok_result['short_r2_mean']:.3f}, "
                f"recall={havok_result['recall']:.3f}, "
                f"precision={havok_result['precision']:.3f}, "
                f"bursts={havok_result['n_true_bursts']}"
            )

        except Exception as e:
            print(f"Failed for {param_name}={value}: {e}")

            results.append({
                param_name: value,
                "lambda_max": np.nan,
                "recall": np.nan,
                "precision": np.nan,
                "mean_lead": np.nan,
                "short_r2_mean": np.nan,
                "n_true_bursts": np.nan,
                "n_pred_bursts": np.nan,
            })

    return results


# ============================================================
# Plotting
# ============================================================

def plot_sweep_results(results, param_name):
    values = np.array([r[param_name] for r in results])
    lambdas = np.array([r["lambda_max"] for r in results])
    recalls = np.array([r["recall"] for r in results])
    precisions = np.array([r["precision"] for r in results])
    leads = np.array([r["mean_lead"] for r in results])
    r2_vals = np.array([r["short_r2_mean"] for r in results])

    fig, axes = plt.subplots(1, 4, figsize=(20, 4))

    axes[0].plot(values, lambdas, "o-", lw=2)
    axes[0].axhline(0, c="k", ls="--", lw=1)
    axes[0].set_xlabel(param_name)
    axes[0].set_ylabel(r"$\lambda_{max}$")
    axes[0].set_title("Chaos vs parameter")

    axes[1].plot(values, recalls, "o-", lw=2, label="Recall")
    axes[1].plot(values, precisions, "s--", lw=2, label="Precision")
    axes[1].set_xlabel(param_name)
    axes[1].set_ylabel("Score")
    axes[1].set_ylim(0, 1.05)
    axes[1].set_title("Burst prediction vs parameter")
    axes[1].legend()

    axes[2].scatter(lambdas, recalls, s=60, label="Recall")
    axes[2].scatter(lambdas, precisions, s=60, label="Precision")
    axes[2].axvline(0, c="k", ls="--", lw=1)
    axes[2].set_xlabel(r"$\lambda_{max}$")
    axes[2].set_ylabel("Score")
    axes[2].set_ylim(0, 1.05)
    axes[2].set_title("Burst prediction vs chaos")
    axes[2].legend()

    sc = axes[3].scatter(lambdas, r2_vals, c=values, s=80, edgecolor="k")
    axes[3].axvline(0, c="k", ls="--", lw=1)
    axes[3].set_xlabel(r"$\lambda_{max}$")
    axes[3].set_ylabel(r"Mean windowed $R^2$")
    axes[3].set_title("Short-term prediction vs chaos")
    cbar = plt.colorbar(sc, ax=axes[3])
    cbar.set_label(param_name)

    plt.tight_layout()
    plt.show()

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(values, leads, "o-", lw=2)
    axes[0].set_xlabel(param_name)
    axes[0].set_ylabel("Mean lead time")
    axes[0].set_title("Prediction lead time vs parameter")

    sc = axes[1].scatter(lambdas, r2_vals, c=values, s=80, edgecolor="k")
    axes[1].axvline(0, c="k", ls="--", lw=1)
    axes[1].set_xlabel(r"$\lambda_{max}$")
    axes[1].set_ylabel(r"Mean windowed $R^2$")
    axes[1].set_title(f"Mean windowed $R^2$ vs chaos ({param_name})")
    cbar = plt.colorbar(sc, ax=axes[1])
    cbar.set_label(param_name)

    plt.tight_layout()
    plt.show()


# ============================================================
# Run experiment
# ============================================================

base_params = {
    "a": 1.0,
    "b": 3.0,
    "c": 1.0,
    "d": 5.0,
    "r": 0.0021,
    "s": 4.0,
    "x_rest": -1.6,
    "I_ext": 3.281,
}

baseline = run_single_havok_analysis(
    base_params,
    dt=0.1,
    m=120000,
    prediction_window=20.0,
    short_window_size=200,
    n_short_windows=100,
    make_plot=True
)

baseline_lambda = estimate_largest_lyapunov(base_params)

print("\nBASELINE RESULTS")
print(f"True bursts:               {baseline['n_true_bursts']}")
print(f"Predicted bursts:          {baseline['n_pred_bursts']}")
print(f"Recall:                    {baseline['recall']:.3f}")
print(f"Precision:                 {baseline['precision']:.3f}")
print(f"Mean lead time:            {baseline['mean_lead']:.2f}")
print(f"Windowed short-term R²:    {baseline['short_r2_mean']:.3f}")
print(f"Largest Lyapunov exponent: {baseline_lambda:.5f}")


# I_ext sweep
I_values = np.linspace(3.05, 3.50, 20)

I_results = sweep_parameter(
    "I_ext",
    I_values,
    base_params,
    dt=0.1,
    m=80000,
    lyap_total_time=1500.0,
    prediction_window=20.0,
    short_window_size=200,
    n_short_windows=100,
)

plot_sweep_results(I_results, "I_ext")


# r sweep
r_values = np.linspace(0.0012, 0.0034, 20)

r_results = sweep_parameter(
    "r",
    r_values,
    base_params,
    dt=0.1,
    m=80000,
    lyap_total_time=1500.0,
    prediction_window=20.0,
    short_window_size=200,
    n_short_windows=100,
)

plot_sweep_results(r_results, "r")